version: '3'
services:
  db:
    image: 'mysql:5.7'
    restart: always
    volumes:
      - D:\db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=development_test
    ports:
      - "3306:3306"